export enum CourseType {
  UNIVERSITY_MANDATORY = 'UNIVERSITY_MANDATORY',
  UNIVERSITY_ELECTIVE = 'UNIVERSITY_ELECTIVE',
  COLLEGE_MANDATORY = 'COLLEGE_MANDATORY',
  COLLEGE_ELECTIVE = 'COLLEGE_ELECTIVE',
  DEPARTMENT_MANDATORY = 'DEPARTMENT_MANDATORY',
  DEPARTMENT_ELECTIVE = 'DEPARTMENT_ELECTIVE',
}


